### ISSUE TITLE
Can't Set Up Scene

### ISSUE THREAD

**Issue by Armandeus66** [MeusRex/pf2e-chex#17]
I can't seem to get this to work at all. I even tried making a new scene, with nothing but a row-odd hex grid, then activating cHex for the scene. I can't paint any terrain onto the hex grid. I get the paint terrain tool to show, but it does nothing.

I want to use this for the Danger Island map of Fists of the Ruby Phoenix, to make it easy for the players to see how many movement points each hex uses up.

Would you please give a step-by-step explanation for dummies about how to set up a scene for cHex? I see here what you can do, but not how to set it up. Thanks!

I think you might be able to use the World Explorer module to cover unexplored hexes with an overlain image. However, I disabled that and made a completely new scene and still couldn't get cHex to paint terrain values.

**Comment by Ackerfe** [comment]
have you clicked the button that shows the chex grid? it's in the token controls section of the left sidebar
You click a button there to show the chex grid, then you click a button there to show the terrain overlay and then you can paint the terrain tiles using the terrain palette tool

**Comment by MeusRex** [comment]
It's currently not well solved, since you have to constantly switch between the two categories of tools. As Ackerfe said, you can only draw when the overlay under Token is active. But at the same time, you then need to switch back to the chex tool, as otherwise you will not be able to draw. (If you get a selection box when click dragging you are in the wrong tool category.)

I'm currently working on a full refactor of the code in this branch: https://github.com/MeusRex/pf2e-chex/tree/TS-and-knockout
(I'm done with the move of js -> ts and about 50% of handlebars -> knockout. Not everything is pushed to the branch atm.)
In this refactor I plan to move all tools relevant for chex to the chex tool category. This should hopefully make all this clearer. With a bit of luck I should manage to push a new version towards the end of this week.

**Comment by Armandeus66** [comment]
Thanks for the answers and the work on this module. I hadn't thought to look in a different menu.

**Comment by MeusRex** [comment]
Thanks, ya, you ain't the only one who had this problem. That's how you know it's bad design. Since this should have resolved your issue I'm closing this ticket. If you still have issues you can reopen it or start a new one.
