### ISSUE TITLE
Toggling the terrain or travel overlays freezes Foundry

### ISSUE THREAD

**Issue by GetJaped** [MeusRex/pf2e-chex#26]
Unsure what causes this, but it appears the game remains running, I just can no longer interact with anything when I enable one of those two overlays.

**Comment by MeusRex** [comment]
Do you have any particular large regions/continuous blocks of one color? The current implementation slows down the more edges there are in one single region. For example, for me, it takes longer to switch to Kingdom view, then it takes switching between the two others.

Also, do you have any error messages in the browser console? (F12) If yes, they would be helpful.

I'm currently working on a complete redesign of cHex that will fix a lot of the slowdown issues on bigger maps. But I don't have nearly as much time to work on it as I'd like. So that one will be a while.

**Comment by GetJaped** [comment]
Actually, now that you told me that it could be because of image size, I tried again due to me having recently compressed the image and it worked fairly well, so it was indeed just the size of the image for the map that was the issue. It was somewhat slow, but slow is better than frozen lmao.
